#!mast .ruby .yaropts bin lib spec test [A-Z]*.*
.ruby
lib/spectroscope/context.rb
lib/spectroscope/example.rb
lib/spectroscope/hooks.rb
lib/spectroscope/world.rb
lib/spectroscope.rb
lib/spectroscope.yml
spec/hooks_spec.rb
spec/let_spec.rb
spec/scope_spec.rb
spec/shared_example_spec.rb
spec/subject_spec.rb
LICENSE.txt
HISTORY.md
README.md
COPYING.rdoc
