#!mast .ruby .yaropts bin lib spec test [A-Z]*.*
.ruby
lib/spectra/describe.rb
lib/spectra/example.rb
lib/spectra/hooks.rb
lib/spectra/world.rb
lib/spectra.rb
lib/spectra.yml
spec/hooks_spec.rb
spec/let_spec.rb
spec/scope_spec.rb
spec/shared_example_spec.rb
spec/subject_spec.rb
LICENSE.txt
HISTORY.md
README.md
COPYING.rdoc
