#!/usr/bin/env ruby

name    'spectra'
version '0.1.0'
title   'Spectra'
summary 'RSpec-like BDD on RubyTest'
created '2012-02-22'

description 'Spectra is a BDD framework built on RubyTest designed to emulate ' \
            'RSpec in most respects.'

resources 'home' => 'http://rubyworks.github.com/spectra',
          'code' => 'http://github.com/rubyworks/spectra',
          'mail' => 'http://groups.google.com/groups/rubyworks-mailinglist'

repositories 'upstream' => 'git://github.com/proutils/spectra.git'

requirements [
  'rubytest',
  'detroit  (build)',
  'reap     (build)',
  'ae       (test)'
]

organization 'RubyWorks'

authors [
  'Trans <transfire@gmail.com>'
]

copyrights [
  '2012 Rubyworks (BSD-2-Clause)'
]

