#!/usr/bin/env ruby

name    'spectroscope'
version '0.1.0'

title   'Spectroscope'
summary 'RSpec-like BDD on RubyTest'
created '2012-02-22'

description 'Spectroscope is a BDD framework built on RubyTest designed to emulate ' \
            'RSpec in most respects. It is assertion framework independent so ' \
            'any number of assertion systems can be used, such as Assay or AE.' 

resources 'home' => 'http://rubyworks.github.com/spectroscope',
          'code' => 'http://github.com/rubyworks/spectroscope',
          'mail' => 'http://groups.google.com/groups/rubyworks-mailinglist'

repositories 'upstream' => 'git://github.com/proutils/spectroscope.git'

requirements [
  'rubytest',
  'detroit  (build)',
  'reap     (build)',
  'mast     (build)',
  'ae       (test)'
]

organization 'RubyWorks'

authors [
  'Trans <transfire@gmail.com>'
]

copyrights [
  '2012 Rubyworks (BSD-2-Clause)'
]

